name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to use package.json version)'
        required: false
        type: string
      tag:
        description: 'npm tag (latest, beta, next, etc.)'
        required: false
        default: 'latest'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Set version (if provided)
        if: ${{ github.event.inputs.version }}
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Publish to npm (release)
        if: github.event_name == 'release'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm (manual)
        if: github.event_name == 'workflow_dispatch'
        run: npm publish --access public --tag ${{ github.event.inputs.tag || 'latest' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}