name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (major, minor, patch) or specific version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.version }} -m "chore: bump version to %s"
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Push changes
        run: |
          git push
          git push --tags

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: bump version to v${{ env.NEW_VERSION }}'
          title: 'chore: bump version to v${{ env.NEW_VERSION }}'
          body: |
            ## Version Bump to v${{ env.NEW_VERSION }}

            This PR was automatically created by the version bump workflow.

            ### Type of change
            - Version bump: `${{ github.event.inputs.version }}`

            ### Checklist
            - [ ] Version number updated in package.json
            - [ ] Changelog updated (if needed)
            - [ ] All tests pass
          branch: version-bump-${{ env.NEW_VERSION }}
          delete-branch: true